Repository OutcastsGameStudio/LP, pull requests merged in 2025-05, with the labels that each got.

#427 Added Crouch feature
  Content/Characters/BP_SR_Character.uasset
  Content/Characters/Input/Actions/IA_Crouch.uasset
  Content/Characters/Input/IMC_Default.uasset
  Source/SR/Character/Components/ContextState/SR_ContextStateComponent.cpp
  Source/SR/Character/Components/ContextState/SR_ContextStateComponent.h
  Source/SR/Character/Components/Slide/SR_SlideComponent.cpp
  Source/SR/Character/Components/Slide/SR_SlideComponent.h
  Source/SR/Character/SR_Character.cpp
  Source/SR/Character/SR_Character.h
Labels: Dev

#436 Added Panel control system
  Binaries/Win64/UnrealEditor-SR.patch_14.exp
  Binaries/Win64/UnrealEditor-SR.patch_15.exp
  Binaries/Win64/UnrealEditor-SR.patch_16.exp
  Binaries/Win64/UnrealEditor-SR.patch_17.exp
  Binaries/Win64/UnrealEditor-SR.patch_18.exp
  Content/Maps/Maps_Test/ConsolePlatformSystem/BP_PanelControl_01.uasset
  Content/Maps/Maps_Test/ConsolePlatformSystem/BP_PanelControl_02.uasset
  Content/Maps/Maps_Test/ConsolePlatformSystem/BP_PanelControl_03.uasset
  Content/Maps/Maps_Test/ConsolePlatformSystem/PlatformControlled01/BP_PLatform_01.uasset
  Content/Maps/Maps_Test/ConsolePlatformSystem/PlatformControlled01/BP_PLatform_04.uasset
  Content/Maps/Maps_Test/ConsolePlatformSystem/PlatformControlled01/BP_Platform_02.uasset
  Content/Maps/Maps_Test/ConsolePlatformSystem/PlatformControlled01/BP_Platform_03.uasset
  Content/Maps/Maps_Test/ConsolePlatformSystem/PlatformControlled01/BP_Platform_05.uasset
  Content/Maps/Maps_Test/Level_GymPlayer.umap
  Source/SR/GameplayObjects/PanelControlSystem/SR_PanelControl.cpp
  Source/SR/GameplayObjects/PanelControlSystem/SR_PanelControl.h
  Source/SR/GameplayObjects/PlatformSystem/SR_BridgePlatform.cpp
  Source/SR/GameplayObjects/PlatformSystem/SR_BridgePlatform.h
Labels: Dev

#440 Fixed crash engine, deleted DebugComponent
  Content/UI/DebugSystem/WBP_PlayerVariables.uasset
  Content/UI/DebugSystem/WBP_PlayerVariablesShow.uasset
  Source/SR/Character/SR_Character.cpp
  Source/SR/Character/SR_Character.h
  Source/SR/GameMode/SR_GameMode.cpp
Labels: Dev

#452 PISTON_Room + Container + polish
  Content/Enviro/Props/A_Ranger/S_Ceiling.uasset
  Content/Enviro/Props/A_Ranger/S_Ground_Ramp.uasset
  Content/Enviro/Props/Props_Maps_Contener/Corridors_Props_TomV/MeshCorridor/S_Door/S_BorderDoor.uasset
  Content/Enviro/Props/Props_Maps_Contener/GH_Dorian_Part/Retake/HangarDoor_Wall1_GH.uasset
  Content/Enviro/Props/Props_Maps_Contener/GH_Dorian_Part/Retake/HangarDoor_Wall2_GH.uasset
  Content/Enviro/Props/Props_Maps_Contener/GH_Dorian_Part/Retake/HangarDoor_Wall3_GH.uasset
  Content/Enviro/Props/Props_Maps_Contener/GH_Dorian_Part/Retake/Large_Cargo_Open_GH.uasset
  Content/Enviro/Props/Props_Maps_Contener/LR_Guillaume/Other/S_Container.uasset
  Content/Enviro/Props/Props_Maps_Contener/LR_Guillaume/Pillars/S_Pillar_Mid.uasset
  Content/Enviro/Props/Props_Maps_Contener/LR_Guillaume/PressRoom/MI_PressGround.uasset
  Content/Enviro/Props/Props_Maps_Contener/LR_Guillaume/PressRoom/MI_PressPistonCase.uasset
  Content/Enviro/Props/Props_Maps_Contener/LR_Guillaume/PressRoom/M_PressGround.uasset
  Content/Enviro/Props/Props_Maps_Contener/LR_Guillaume/PressRoom/M_PressPistonCase.uasset
  Content/Enviro/Props/Props_Maps_Contener/LR_Guillaume/PressRoom/S_PressGround.uasset
  Content/Enviro/Props/Props_Maps_Contener/LR_Guillaume/PressRoom/S_PressPiston.uasset
  Content/Enviro/Props/Props_Maps_Contener/LR_Guillaume/PressRoom/S_PressPistonCase.uasset
  Content/Enviro/Props/Props_Maps_Contener/LR_Guillaume/Rails/M_Rail.uasset
  Content/Enviro/Props/Props_Maps_Contener/LR_Guillaume/Rails/S_Rail_Attach.uasset
  Content/Enviro/Props/Props_Maps_Contener/LR_Guillaume/Walls/S_Wall_Extrude.uasset
  Content/Enviro/Props/Props_Maps_Contener/LR_Guillaume/Walls/S_Wall_Hole.uasset
  Content/Enviro/Props/Props_Maps_Contener/Pipes/P2_6M.uasset
  Content/Maps/Container_02/L_BArt_Container_02_SubLevel/L_BArt_Container_EndCorridor_Retake.umap
  Content/Maps/Container_02/L_BArt_Container_02_SubLevel/L_BArt_Container_Press.umap
  Content/Maps/Container_02/L_BArt_Container_02_SubLevel/L_BArt_Container_Rail.umap
  Content/Maps/Container_02/L_BArt_Container_02_SubLevel/L_BArt_Container_StartCorridor.umap
  Content/Maps/Container_02/L_BArt_Container_02_SubLevel/L_BArt_Container_WallDeco.umap
  Content/Maps/Container_02/L_Container_02.umap
  Content/Maps/Maps_Blocking_Alexandre/LD_Tools_Alexandre/BP/BP_Contener.uasset
  Content/Maps/Maps_Blocking_Alexandre/LD_Tools_Alexandre/BP/BP_Press.uasset
Labels: DESIGN, Art, Dev

#455 Patch
  Content/Design/Widgets_Player/Images/CreditButton.uasset
  Content/Design/Widgets_Player/Images/Credits.uasset
  Content/Design/Widgets_Player/Images/Illustration_Last_Pulse.uasset
  Content/Design/Widgets_Player/Images/crosshair.uasset
  Content/Design/Widgets_Player/WBP_FailureScreen.uasset
  Content/Design/Widgets_Player/WBP_Menu.uasset
  Content/Design/Widgets_Player/WBP_PlayerUi.uasset
  Content/Maps/Container_02/L_BArt_Container_02_SubLevel/L_BArt_Container_ClosedRoom.umap
  Content/Maps/Container_02/L_BArt_Container_02_SubLevel/L_BArt_Container_EndCorridor_Retake.umap
  Content/Maps/Container_02/L_BArt_Container_02_SubLevel/L_BArt_Container_Press.umap
  Content/Maps/Container_02/L_BGD_Container_02_SubLevel/L_BGD_Container_GdTool.umap
  Content/Maps/Container_02/L_Container_02.umap
  Content/Maps/Map_Menu/Level_Menu.umap
  Content/Maps/Maps_Blocking_Alexandre/LD_Tools_Alexandre/BP/BP_Press.uasset
  Content/System/Menu/WB_PausInfo.uasset
Labels: DESIGN, Art, Dev

#457 Add music and load robotroom instantly
  Content/Maps/Container_02/L_Container_02.umap
  Content/Maps/Map_Menu/Level_Menu.umap
Labels: Art

#463 killzone + crouch
  Content/Enviro/Props/Props_Maps_Contener/GH_Second_Part_Luca/Contour_Trou_Cr.uasset
  Content/Enviro/Props/Props_Maps_Contener/GH_Second_Part_Luca/Wall_Cr_Broken.uasset
  Content/Maps/Container_02/L_BArt_Container_02_SubLevel/L_BArt_Container_Press.umap
  Content/Maps/Container_02/L_BGD_Container_02_SubLevel/L_BGD_Container_Press_03.umap
  Content/Maps/Container_02/L_Container_02.umap
  Content/Maps/Maps_Blocking_Alexandre/LD_Tools_Alexandre/BP/BP_BoxTriggerPress.uasset
  Content/Maps/Maps_Blocking_Alexandre/LD_Tools_Alexandre/BP/BP_Press.uasset
  SR.uproject
Labels: DESIGN, Art, Dev

#478 added scaffolding
  Content/Maps/Container_02/L_BArt_Container_02_SubLevel/L_BArt_Container_WallDeco.umap
  Content/Maps/Container_02/L_Container_02.umap
Labels: KAMISAMA

#481 Fixed Build error
  Binaries/Win64/SR-Win64-Shipping.exp
  Binaries/Win64/SR-Win64-Shipping.target
  Binaries/Win64/SR.exp
  Binaries/Win64/SR.target
  Binaries/Win64/UnrealEditor-SR.patch_0.exp
  Config/DefaultEngine.ini
  Config/DefaultGame.ini
  Content/Design/Widgets_Player/WBP_Menu.uasset
  Content/Maps/Map_Menu/Level_Menu.umap
  Content/System/GameModes/Base/BP_LP_Mode.uasset
  Content/System/GameModes/Base/BP_SR_GameModeBase.uasset
  SR.uproject
  Source/SR/GameMode/SR_GameMode.cpp
  Source/SR/GameMode/SR_GameMode.h
Labels: Dev, KAMISAMA

#484 Fixed Respawn error
  Content/Design/Widgets_Player/WBP_FailureScreen.uasset
  Content/Maps/Container_02/L_BGD_Container_02_SubLevel/L_BGD_Container_GdTool.umap
  Content/Maps/Maps_Blocking_Alexandre/LD_Tools_Alexandre/BP/KillBoxAndMore/BP_Checkpoint_Manager.uasset
Labels: Dev, KAMISAMA

#487 FIxed respawn
  Binaries/Win64/UnrealEditor-SR.patch_3.exp
  Content/Maps/Container_02/L_BGD_Container_02_SubLevel/L_BGD_Container_GdTool.umap
Labels: Dev, KAMISAMA
